# Fuchsia Format Style
# last reviewed: Feb 27, 2023
# Fuchsia uses mostly 2021 edition
edition = "2021"
# The "Default" setting has a heuristic which splits lines too aggresively.
# We are willing to revisit this setting in future versions of rustfmt.
# Bugs:
#   * https://github.com/rust-lang/rustfmt/issues/3119
#   * https://github.com/rust-lang/rustfmt/issues/3120
use_small_heuristics = "Max"
# Prevent carriage returns
newline_style = "Unix"
# We use 2 spaces for indentation
tab_spaces = 2
